version: '3.8'

services:
  blog-backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=production
      - N8N_BASE_URL=https://primary-production-e91c.up.railway.app/webhook-test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  blog-frontend:
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - blog-backend
    restart: unless-stopped
